# --- Define basic settings --- #
executor:         cluster-generic
latency-wait:     5
rerun-incomplete: true
jobs:             100
use-singularity:  true
use-conda:        true

# --- Define the generic cluster submit command --- #
cluster-generic-submit-cmd: bsub -W {resources.runtime} -n 12 -M {resources.mem_mb} -P {resources.project} -q {resources.queue} -R {resources.span} -oo clusterlogs/%J.OU

# --- Define default resources for all rules --- #
default-resources:
  mem_mb:   25000
  queue:    "express"
  project:  "acc_PVI"
  runtime:  "12h"
  span:     "\"span[hosts=1]\""

# --- Define rule-specific resources --- #
